# sudo: required
language: node_js
node_js:
  - 12
services:
  - docker

before_install:
  - docker build  -t andicirjaliu/td_react -f Dockerfile.dev .

script:
  - docker run andicirjaliu/td_react npm run test -- --coverage --watchAll=false

# deploy:
#    provider: cloudfoundry
#    username: andi.cirjaliu@ro.ibm.com
#    password: supersecretpassword
#    api: https://api.run.pivotal.io
#    organization: 
#    space: 
  #  manifest: manifest-staging.yml       # (optional)  Defaults to manifest.yml.
  #  app_name: My app name                # (optional)