# sudo: required
language: node_js
node_js:
  - 12
services:
  - docker

before_install:
  - docker build  -t andicirjaliu/td_react -f Dockerfile.dev .

script:
  - docker run andicirjaliu/td_react npm run test -- --coverage --watchAll=false