# sudo: required
language: node.js
services:
  - docker

before_install:
  - docker build  -t andicirjaliu/td_react -f Dockerfile.dev .

script:
  - docker run andicirjaliu/td_react npm run test -- --coverage --watchAll=false